---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ao.
--- DateTime: 2025/6/13 18:38
---

-- 参数列表
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 数据key
local stockKey = 'seckill:stock:'.. voucherId
local orderKey = 'seckill:order:'.. voucherId

-- 业务
-- 判断库存是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    -- 库存不足
    return 1
end
--  判断用户是否已经下过单
if (redis.call('sismember',orderKey,userId) ==1) then
    -- 已经下过
    return 2
end
-- 库存-1
redis.call('incrby',stockKey,-1)
-- 加入set集合中
redis.call('sadd',orderKey,userId)
return 0